x-default-logging: &logging
  driver: "syslog"
  options:
    syslog-address: "udp://host.docker.internal:5514"
    syslog-format: rfc5424
    tag: "{{.Name}}"

services:
  prometheus:
    logging: *logging
    volumes:
      # Scrape the Otel Collector With Prometheus Instead of having it scrape itself
      - ../../components/prometheus/config/scrape_configs/scrape_otel.yaml:/etc/prometheus/scrape_configs/scrape_otel.yaml
      - ../../components/prometheus/config/scrape_configs/scrape_grafana.yaml:/etc/prometheus/scrape_configs/scrape_grafana.yaml