---
version: "3.7"

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.55.1
    restart: unless-stopped
    user: 0:0
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./config/scrape_configs/scrape_prometheus.yaml:/etc/prometheus/scrape_configs/scrape_prometheus.yaml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--enable-feature=otlp-write-receiver'
