apiVersion: 1

datasources:
- name: ClickHouse
  type: grafana-clickhouse-datasource
  jsonData:
    defaultDatabase: otel
    port: 9000
    server: clickhouse
    username: grafana
    tlsSkipVerify: true
  secureJsonData:
    password: $GRAFANA_CLICKHOUSE_PASSWORD
    # tlsCACert:     <string> # TLS CA certificate
    # tlsClientCert: <string> # TLS client certificate
    # tlsClientKey:  <string> # TLS client key
