receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "${env:HOSTNAME}:4317"
      http:
        endpoint: "${env:HOSTNAME}:4318"
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

processors:
  batch:

exporters:
  debug:
    verbosity: basic
    sampling_initial: 5
    sampling_thereafter: 200
  debug/detailed:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]