---
version: "3.7"

volumes:
  grafana_data: {}

services:
  grafana:
    image: grafana/grafana:11.3.1
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    volumes:
      - grafana_data:/var/lib/grafana
