version: '3'

volumes:
  clickhouse_data:

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    user: "101:101"
    hostname: clickhouse
    volumes:
      - ./config/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./config/users.d/user-default.xml:/etc/clickhouse-server/users.d/user-default.xml
      - ./config/docker-entrypoint-initdb.d/init-otel-db.sh:/docker-entrypoint-initdb.d/init-otel-db.sh
      - clickhouse_data:/var/lib/clickhouse
    env_file: ".env"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
